Don't return NULL from rd_kafka_new()'s "This should never happen" codepath
confluentinc/librdkafka pull request #4112
Opened 2022-12-16 19:41 UTC by Quuxplusone

As the new comment says: We shouldn't return NULL unless failure has actually occurred and our caller can proceed with cleaning up their resources. If librdkafka is still actively running background threads that need to touch those resources, we MUST NOT communicate otherwise to our caller.

Since this codepath "should never happen," it theoretically doesn't matter much what we do here. But `return NULL` in practice leads to use-after-free segfaults on overloaded VMs, so we shouldn't do that. Instead, just loop (and log) until the background threads have run, and then proceed. Slow success is still success.

Fixes #4100.

2022-12-16 20:15 UTC, edenhill requested changes

2022-12-16 20:15 UTC, edenhill commented on src/rdkafka.c
> +                             rk->rk_name, rk->rk_init_wait_cnt, 60*i);
60*i is likely to not be correct on heavily loaded vms, so recommend just skipping the %d seconds timeout and instead add what it will do, e.g., "Still waiting for %s background thread(s) to initialize".

Replace the for loop with a while, since `i` is no longer needed, alternatively make it assert after 3 attempts (e.g., 3 minutes).

2022-12-16 21:46 UTC, Quuxplusone commented on src/rdkafka.c
> +                             rk->rk_name, rk->rk_init_wait_cnt, 60*i);
These messages will show up in /var/log/messages with timestamps, so the durations _after the first one_ don't need to be the primary source of truth. I agree with your assessment that the first duration isn't likely to be exactly 60 seconds either. Does librdkafka have a way of telling what time it is? If so, we could update this codepath to print the _actual_ duration elapsed (`now() - start_time`). Alternatively, we can print "Waited _at least_ %d seconds for..."; pending more discussion, for now I'll just update the patch in that direction.

Assert-failing is clearly better than returning NULL and segfaulting; but it's not clearly better than just continuing to loop forever and relying on the operator to `kill -9` the process. At least for our own codebase, we'll prefer to loop forever. Notice that we (the client programmer) will be seeing this message sent to our logging callback every 60 seconds forever, and we can choose to `abort` after 1 or 3 or 300 printings of the message, if we feel like it. I don't think librdkafka needs to take on that responsibility itself.

2022-12-16 22:35 UTC, edenhill commented on src/rdkafka.c
> +                             rk->rk_name, rk->rk_init_wait_cnt, 60*i);
This is a really niche problem, so let's keep this as simple as possible.
If the system is loaded it couldn't spin up the background threads in over a minute, it won't be very useful for anything anyway, so why not just assert?

2022-12-17 00:39 UTC, Quuxplusone commented on src/rdkafka.c
> +                             rk->rk_name, rk->rk_init_wait_cnt, 60*i);
AFAICT right now: in our own codebase we won't assert, so if upstream asserts, we'll have to patch it. This is not a big deal (we certainly need to patch it anyway, from today until whenever we upgrade to 2.0+), but it would be _nice_ if the future-upstream just looked perfect from our POV and didn't still need patching.

I still think the simple thing is just "wait until all the threads have started, don't try to be clever by hard-coding any specific timeout." Which is what this proposed patch does, at the moment, right?

Alternatively, is there a way to actually fix the root cause here? Like, this code is just waiting 60 seconds and then going "oh no, we spawned off some worker threads and now we can't get them back, _and_ if we return NULL then those worker threads are going to access freed memory when they _do_ get around to running." Could you do something here to mark the leaked `rd_kafka_t` object as "dead" so that when the workers do get around to running, they know not to access any of its config but simply exit? Or ask pthreads to aggressively kill those worker threads so that we know they're dead before we return? or something else along those lines? I think that's probably impossible, but just in case it brings something to mind for you...?

2022-12-19 10:07 UTC, edenhill commented on src/rdkafka.c
> +                             rk->rk_name, rk->rk_init_wait_cnt, 60*i);
I have a hard time understanding how any of this is useful in practice; if your system is so slow it takes minutes to spin up a background thread, then the subsequent of the multi-threaded librdkafka client will most likely be so slow that nothing works anyway. I.e., connects and handshakes will time out, making it so that there is no usable broker connections, etc.

I do understand that the current behaviour of returning with the background thread still running is problematic for cleanup and late-reference reasons, and we could probably do better.

Killing the background threads might work, but will leak memory and possibly cause deadlocks due to held locks, so we're just transitioning into another unknown state.

So, my suggestion is just to rd_assert() if the background thread hasn't come alive in one minute - it is the only safe thing to do since we can't reason about the current state of things, and we can't clean up properly.

2022-12-19 20:41 UTC, Quuxplusone commented on src/rdkafka.c
> +                             rk->rk_name, rk->rk_init_wait_cnt, 60*i);
@edenhill: I continue to think that the simplest thing is "wait until all the threads have started, don't hard-code any specific timeout."  However, I can see that that idea is unlikely to get adopted by you upstream; meanwhile I'm able to patch the code any way I like downstream.

So I think the appropriate outcome on this PR would be if you'd just commandeer it to add the `rd_kafka_assert(rk, !*"Resource exhaustion: background threads didn't start in 60 seconds")` or `rd_assert(!*"BUG: this should never happen")` or whatever you think is the appropriate way to assert-fail here — and also presumably remove the `rd_kafka_set_last_error` and `rd_snprintf` but presumably _not_ the `rd_kafka_log`. I could try to guess at those changes, but there are so many different ways it _might_ be done that I think it's easier if you do it.
That'll address the use-after-free bug; and then everything else I can handle via downstream patches.

2023-01-10 19:13 UTC, Quuxplusone commented
We have handled this downstream by adding the loop exactly as in my original PR.

2023-01-10 19:13 UTC, closed without merging