Fix close blocked by refcnt in test 0113.
confluentinc/librdkafka pull request #4187
Opened 2023-02-10 13:44 UTC by emasab

Breaks a circular dependency from
rko to rktp and back that prevents
the toppar being destroyed.

2023-02-14 08:59 UTC, milindl commented
I see that the assertion fails, here https://confluentinc.semaphoreci.com/jobs/f3de9229-85de-4bb0-914f-3daf8b1f89d3#L5575

2023-02-14 09:07 UTC, emasab commented
@milindl : seen that, I'm looking for a different fix.

2023-02-23 10:48 UTC, milindl approved these changes
lgtm, with addition comment for more clarity requested

2023-02-23 10:48 UTC, milindl commented on src/rdkafka_cgrp.c
> +                        rd_assert(rko->rko_type == RD_KAFKA_OP_BARRIER);
Minor: Comment here explaining why we check only for barrier would be helpful

2023-02-23 11:28 UTC, pranavrth requested changes

2023-02-23 11:28 UTC, pranavrth commented on src/rdkafka_cgrp.c
> +                                     "Purge toppar buffer containing %d "
Lets add "fetch queue" as well in the debug logs.

2023-02-23 11:28 UTC, pranavrth commented on src/rdkafka_cgrp.c
> +                                     "Not purging toppar buffer");
Lets add "fetch queue" as well in the debug logs.

2023-03-02 11:11 UTC, pranavrth reviewed
Looks good. Just some minor improvements.

2023-03-02 11:11 UTC, pranavrth commented on src/rdkafka_cgrp.c
> +                while ((rko = next)) {
I don't think `next` is necessary. We can use:

```c
while (rko) {

   rko = TAILQ_NEXT(rko, rko_link);
}
```

2023-03-02 11:11 UTC, pranavrth commented on src/rdkafka_cgrp.c
> +                                     "Not purging toppar fetch queue buffer");
Can also add `No ops present in the buffer`.

2023-03-10 07:35 UTC, emasab commented
@pranavrth no, it's just for leaving the CHANGELOG always ready for a release.

2023-03-10 09:53 UTC, merged