Fix timeout for rd_kafka_query_watermark_offsets
confluentinc/librdkafka pull request #4460
Opened 2023-10-10 04:23 UTC by milindl

`rd_kafka_query_watermark_offsets` hangs forever if say, the broker is down, and exceeds the timeout in case the RTT > timeout, see the linked issue.

This PR adds a failing test, and then fixes the issue.

This also changes the fact the return value of `rd_kafka_q_serve` was being compared to RD_KAFKA_OP_RES_YIELD, which doesn't make sense to me, since it returns the count of served ops, and RD_KAFKA_OP_RES_YIELD is a positive constant.

Fixes #2588.

2023-10-10 15:25 UTC, emasab requested changes
Thanks for the fix! Just some test changes to ensure it's run when the test run has the local flag

2023-10-10 15:25 UTC, emasab commented on CHANGELOG.md
> + * Fix `rd_kafka_query_watermark_offsets` hanging forever (#4460).
```suggestion
 * Fix `rd_kafka_query_watermark_offsets` continuing beyond timeout expiry (#4460).
```

2023-10-11 05:18 UTC, milindl commented on src/rdkafka.c
> +                rd_kafka_q_serve(rkq, tmout, 0, RD_KAFKA_Q_CB_CALLBACK,
Thanks!

2023-10-11 05:18 UTC, milindl commented on tests/0031-get_offsets.c
> +        if (test_quick)
Done, the older test is now untouched and a new main is added.

2023-10-11 05:18 UTC, milindl commented
Addressed comments, thanks for review @emasab

2023-10-11 07:50 UTC, emasab approved these changes
Thanks @milindl !

2023-10-11 07:52 UTC, merged