Purge brokers no longer reported in metadata
confluentinc/librdkafka pull request #4557
Opened 2023-12-12 21:33 UTC by mfleming

Brokers that are not in the metadata should be purged from the internal client lists. This helps to avoid annoying "No route to host" and other connection failure messages.

Fixes #238

2024-05-16 16:32 UTC, emasab requested changes
Hi @mfleming thanks a lot for this contribution and sorry for letting it wait for long. We want to include these fixes in next version. Both fixes are good, just on broker decommission we want to do some additional checks.

Here are some comments mainly for the first fix:

2024-05-16 16:32 UTC, emasab commented on tests/0145-broker-same-host-port.c
Please change this test number to 0149

2024-05-16 16:32 UTC, emasab commented on tests/0146-purge-brokers.c
Please change this test number to 0150

2024-05-16 16:32 UTC, emasab commented on src/rdkafka_broker.c
There are a few things to remove for updating brokers by matching just the id:

- in `rd_kafka_broker_op_serve`, `updated` becomes a `rd_bool_t`
- condition that checks if nodeid has changed has to be removed
- corresponding action and `rd_kafka_broker_map_partitions` needs to be removed.
- `RD_KAFKA_BROKER_STATE_UPDATE` is to be removed

2024-05-21 08:10 UTC, emasab commented
Hi @mfleming can I apply those changes or do you want to continue the PR? Thanks!

2024-05-21 08:17 UTC, mfleming commented
Hey sorry for the delay — yeah you can apply those changes if you have the
time. If not I’ll get to them sometime this week.

On Tue, 21 May 2024 at 09:10, Emanuele Sabellico ***@***.***>
wrote:

> Hi @mfleming <https://github.com/mfleming> can I apply those changes or
> do you want to continue the PR? Thanks!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/confluentinc/librdkafka/pull/4557#issuecomment-2122025277>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAXALUEWS5XRZGGJX6EN43ZDL6QDAVCNFSM6AAAAABASEOCUWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMRSGAZDKMRXG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-06-07 13:20 UTC, emasab commented
@mfleming thanks, sorry for the delay too, I'm checking it again

2024-06-10 13:58 UTC, emasab commented
/sem-approve

2024-06-10 14:19 UTC, emasab commented
/sem-approve

2024-06-12 08:33 UTC, emasab commented
We're not going to merge this for 2.5.0 that is due in July as we need to do more checks on possible regressions but we want to merge it for a maintenance release in September

2024-06-14 13:47 UTC, mfleming commented
> We're not going to merge this for 2.5.0 that is due in July as we need to do more checks on possible regressions but we want to merge it for a maintenance release in September

Thanks for fixing things :)

2024-06-15 11:38 UTC, emasab commented
> Thanks for fixing things :)
Thank you for this PR!

2024-07-01 14:57 UTC, benesch commented
Just wanted to say a big thank you to both of you—@mfleming for writing this and @emasab for reviewing. We just ran into a slow thread leak in a Kafka consumer at @MaterializeInc that will be fixed by this patch.

2024-09-16 23:42 UTC, pranavrth commented
While going through the PR, I found that there is a few issues in the PR.

1. The number of threads are increased as part of this PR. Currently, all the bootstrap servers threads are updated to the real broker thread if they appear in the metadata response. This PR creates new broker threads for the new brokers which are seen in the metadata. The bootstrap servers threads are not reused for this purpose in the PR. Due to this, we generally have 'n*2' brokers threads for 'n' bootstrap servers. Earlier there were only 'n' threads.
2. In the current librdkafka implementation, we always keep bootstrap broker threads even if they are not reported in the metadata. This ensured that we always have bootstrap broker threads if required to rebootstrap. This PR removed this functionality.
3. To fix the issue introduced in point number 2, KIP-899 needs to be implemented.

We need to fix the above issues before releasing this PR and need of more testing. As a result, it won't be part of the upcoming 2.6 release.

2024-10-22 10:11 UTC, emasab commented
Closes #4881

2024-12-13 14:58 UTC, emasab commented
We agreed KIP-899 and KIP-1102 aren't strictly necessary, in Java client they were disabled by default until recently.
The reason is that when a change in broker set happens slow enough to be detected by the periodic (5 min) metadata refresh, the client cannot remain without brokers.

In any case the metadata response contains at least the majority of KRaft elegible brokers. If majority changes, it must contain at least one broker from previous set.
So it's usually not possible the client remains without brokers, unless the set of brokers changes to fast it cannot reach any of them and that's the case KIP-899 and KIP-1102 are addressing. But this last case is also a problem with current librdkafka code so we leave the improvement for a later PR.

There are a few things left to check, at least:

- removing bootstrap brokers without id (-1) and adding brokers with real ids and advertised hostnames.
- check some fields in rd_kafka_s: `no_idemp_brokers, rk_telemetry.preferred_broker, rk_broker_down_cnt, rk_broker_up_cnt, rk_broker_cnt, ...` when brokers are removed. It could help changing the state to DOWN before removing them.
- maybe there's something to change in the stats_cb, but probably nothing to do
- brokers configured with `rd_kafka_brokers_add` must be removed after usage too
- currently, decommissioned threads are still joined on destroy, is it possible to join them from time to time without accumulating them but also without blocking the main thread because of that? At specific intervals maybe, so they're already terminated when joined
- check thoroughly for memory leaks and use-after-free cases

2025-01-10 14:34 UTC, emasab commented
> - check some fields in rd_kafka_s: `no_idemp_brokers, rk_telemetry.preferred_broker, rk_broker_down_cnt, rk_broker_up_cnt, rk_broker_cnt, ...` when brokers are removed. It could help changing the state to DOWN before removing them.

`no_idemp_brokers` seems not being used, `rk_broker_cnt` is decremented in `rd_kafka_broker_thread_main`.  `rk_broker_down_cnt` and `rk_broker_up_cnt` are changed when broker thread receives `RD_KAFKA_OP_TERMINATE`: it calls `rd_kafka_broker_fail` that sets the state to DOWN and changes those counters.

2025-03-05 12:53 UTC, pranavrth requested changes
Went through the implementation on high level. Going to check deeper. Transaction and telemetry needs more understanding. Will connect with you offline on this. Tests and mock broker remaining as well.

2025-03-05 12:53 UTC, pranavrth commented on src/rdkafka_broker.c
> +            rkb->rkb_source == RD_KAFKA_LEARNED &&
Why learned broker is needed for Telemetry subscription call?

2025-03-05 12:53 UTC, pranavrth commented on src/rdkafka_broker.c
> +                rd_kafka_broker_destroy(rkb);
Why this is needed now and was not needed earlier?

2025-03-05 12:53 UTC, pranavrth commented on src/rdkafka_broker.c
> +        rd_dassert(rkb->rkb_state == RD_KAFKA_BROKER_STATE_DOWN);
Is this necessary and correct? Let's not force this and add this later after this patch. Might create a problem if we are reaching here somehow in some other state.

2025-03-13 09:53 UTC, pranavrth requested changes

2025-03-13 09:54 UTC, pranavrth commented
Please check admin client fanout and target all cases as well where we are not using DESTROY_BROKER error.

2025-03-14 12:31 UTC, emasab commented
@mfleming could you please sign the Contributor License Agreement . We'll need it before merging the PR.

2025-03-14 12:39 UTC, mfleming commented
> @mfleming could you please sign the Contributor License Agreement [here](https://ironcladapp.com/public-launch/66bcfa630dec9c9aeb2fc0da) . We'll need it before merging the PR.

Signed.

2025-03-27 11:34 UTC, emasab commented on src/rdkafka_broker.c
> -
We just count the number of logical brokers now (with or without address) and exclude them from broker selection and don't count them for the ALL_BROKERS_DOWN (it'll be one of the learned brokers anyway so it fails at the same time)

2025-03-27 11:46 UTC, emasab commented on src/rdkafka.c
> +                        thrd_join(*thrd, NULL);
It's the last operation sent before terminating the thread and when executed on the main thread it'll be already terminated. Moved sending the operation after the interceptors to avoid block, thanks for spotting it

2025-03-27 11:58 UTC, emasab commented on src/rdkafka.c
> +        rd_list_destroy(&brokers_to_decommission);
It's needed: I've found segmentation faults because of this. Because the decommissioning brokers are removing themselves from the `rk->rk_brokers` queue (rd_kafka_broker_decommission needs to release the lock), even if using `TAILQ_FOREACH_SAFE` some of the decommissioning broker could be destroyed while looping and generate a segfault.

2025-03-27 12:13 UTC, emasab commented on src/rdkafka.c
> +        rd_atomic32_init(&rk->rk_broker_down_cnt, 0);
Because we're not counting the logical broker for the down count, instead it's using the up count in the `connect_any` to subtract it from the total up count.
Given we're only interested to this count for that, we could remove the `rk_logical_broker_up_cnt` as well and only count the learned and configured brokers that are up, but still trigger the monitors for the logical brokers.

2025-03-27 12:14 UTC, emasab commented on src/rdkafka.h
> +int32_t *rd_kafka_brokers_learned_ids(rd_kafka_t *rk, size_t *cntp);
For testing and it's useful for users to check current brokers available in the instance

2025-03-27 12:50 UTC, emasab commented on src/rdkafka_broker.c
> +                    !rd_kafka_terminating(rkb->rkb_rk)) {
Even if this broker is terminating we should report all brokers down, given it's still part of `rk_broker_cnt`

2025-03-27 12:52 UTC, emasab commented on src/rdkafka_broker.c
> +                rd_kafka_broker_destroy(rkb);
It's removed from after sending the TERMINATE op so it's done in a single place and done all the times.

2025-03-27 12:55 UTC, emasab commented on src/rdkafka_broker.c
> +        rd_dassert(rkb->rkb_state == RD_KAFKA_BROKER_STATE_DOWN);
It's `rd_dassert` so will only happen when we configure it with `--enable-devel` so we detect the failure. The state DOWN is (should be always) set just before in `rd_kafka_broker_fail`

2025-03-27 12:58 UTC, emasab commented on src/rdkafka_buf.h
>                          rd_bool_t all_topics;  /**< Full/All topics requested */
It not used anymore, it's currently passed as opaque

2025-03-27 13:08 UTC, emasab commented on src/rdkafka_metadata.c
> +        } while (err == RD_KAFKA_RESP_ERR__DESTROY_BROKER);
Yes because if received a `_DESTROY_BROKER` error from previous broker that won't be returned again from `rd_kafka_broker_any_usable` I can add it to the comment.

2025-03-27 13:15 UTC, emasab commented on src/rdkafka_op.h
> +                        void *rkb;
To enforce that `can only be used for pointer comparison.`

2025-03-27 13:24 UTC, emasab commented on src/rdkafka_topic.c
> +        }
In this case we're not changing the delegation after a metadata update so if it was delegated it will be delegated to the internal broker wiht `rd_kafka_toppar_undelegate` in `rd_kafka_broker_fail` when receiving the TERMINATE op.
It may be that after I've removed the decommissioning broker from the `brokers_by_id` to avoid duplications this isn't needed anymore I'll try without it.

2025-03-27 13:26 UTC, emasab commented on src/rdkafka_metadata.c
> +                    rkb != rkb_current;
It's removed now all configured brokers are removed immediately after getting learned ones.

2025-03-27 13:33 UTC, emasab commented on src/rdkafka.c
> +void rd_kafka_decommissioned_broker_thread_join(rd_kafka_t *rk,
I think it belong here because:

1. it takes `rk` as first parameter
2. it accesses private fields `wait_decommissioned_thrds` and `wait_decommissioned_brokers` from `rk`
3. it's executed in the main thread
4. doesn't touch `rkb` fields as it was already freed.
5. instead of touching the two private fields in `broker.c` we expose this function

2025-03-27 13:38 UTC, emasab commented on src/rdkafka_broker.c
> +        /* Release broker thread reference here and call destroy final. */
This is the last thing it's doing before terminating the thread and there are no additional refcnts that prevent calling `rd_kafka_broker_destroy_final` as for exiting the while loop above they need to be 1 and the additional ones that could be added are removed by purging the ops (in the recent fix).

2025-03-27 13:39 UTC, emasab commented on src/rdkafka_broker.c
> +        return ids;
Do you mean a TAILQ_FILTER?

2025-03-27 13:42 UTC, emasab commented on src/rdkafka_cgrp.c
> +                if (rkb && rkb->rkb_source == RD_KAFKA_LEARNED) {
This isn't needed I think the problem was that `rd_kafka_broker_find_by_nodeid` was returning a decommissioning learned broker but now it's removed already at decommissioning start.

2025-03-27 13:45 UTC, emasab commented on src/rdkafka_metadata.c
> +
Code has changed so now all configured brokers are removed immediately (a consumer metadata refresh fix was needed for it)

2025-03-30 22:47 UTC, pranavrth requested changes

2025-03-31 11:33 UTC, pranavrth requested changes
Checking test part.

2025-03-31 11:33 UTC, pranavrth commented on src/rdkafka_metadata.c
> +                        continue;
As discussed, better to change it to 
```suggestion
                if (rkb->rkb_source == RD_KAFKA_LOGICAL)
                        continue;
```

2025-03-31 11:33 UTC, pranavrth commented on src/rdkafka_metadata.c
> +                        continue;
fine both ways.

2025-03-31 11:33 UTC, pranavrth commented on tests/0149-broker-same-host-port.c
> +                TEST_ASSERT(ids[i] == expected_id,
We should also check host and port.

2025-04-01 10:50 UTC, pranavrth requested changes
Few comments on the test part.

2025-04-01 10:50 UTC, pranavrth commented on src/rdkafka_mock.c
> +                        rd_kafka_mock_coord_destroy(mcluster, mcoord);
`break;` inside `if`.

2025-04-01 10:50 UTC, pranavrth commented on src/rdkafka_mock.c
> +                        mrkb->port = port;
There can be only 1 broker with broker_id. So we can `break;` the loop inside `if`

2025-04-01 10:50 UTC, pranavrth commented on src/rdkafka_mock.c
> -        rd_kafka_broker_destroy(mcluster->dummy_rkb);
Why removing this destroy?

2025-04-01 10:50 UTC, pranavrth commented on src/rdkafka_mock.h
> + * @brief Remove and delete a mock broker from a cluster.
We can add that it triggers reassignment of the partitions as well.

2025-04-01 10:50 UTC, pranavrth commented on src/rdkafka_mock.h
> + * @brief Add a new broker to the cluster.
We can add that it triggers reassignment of the partitions as well.

2025-04-01 10:50 UTC, pranavrth commented on src/rdkafka_mock.c
> +rd_kafka_mock_cluster_reassing_partitions(rd_kafka_mock_cluster_t *mcluster) {
```suggestion
rd_kafka_mock_cluster_reassigning_partitions(rd_kafka_mock_cluster_t *mcluster) {
```

2025-04-01 10:50 UTC, pranavrth commented on tests/0075-retry.c
>                  /* Reject all but the first connect */
Update this comment.

2025-04-01 10:50 UTC, pranavrth commented on tests/0151-purge-brokers.c
> + *         count and value. Sorts \p actual_broker_ids .
It doesn't sort `actual_broker_ids`

2025-04-01 10:50 UTC, pranavrth commented on tests/0151-purge-brokers.c
> +                continue_requesting_metadata &= !fetch_metadata_verify_brokers(
Use logical AND operator instead of bitwise AND operator. Though the result is going to be same here.

2025-04-01 10:50 UTC, pranavrth commented on tests/0151-purge-brokers.c
> +                        continue_requesting_metadata |=
Same change it to logical operator instead of bitwise.

2025-04-01 10:50 UTC, pranavrth commented on tests/0151-purge-brokers.c
> +                TEST_ASSERT(actual_broker_ids[i] == expected_broker_ids[i],
Better to sort `expected_broker_ids` in the function instead of expecting it to be sorted.

2025-04-01 10:50 UTC, pranavrth commented on tests/0151-purge-brokers.c
> +                           size_t expected_broker_ids_cnt,
change this to `action_size` or something like that. We are using this count for other comparison as well.

2025-04-01 10:50 UTC, pranavrth commented on tests/0151-purge-brokers.c
> +                if (action > 0) {
Let's remove this condition altogether. Add a new action to do nothing and add first action in the actions list as that action. Improves readability of the test.

2025-04-01 10:50 UTC, pranavrth commented on tests/0151-purge-brokers.c
> +            {TEST_ACTION_SET_GROUP_COORDINATOR, 5},
How are we verifying that the coordinator is getting updated to the correct one we wanted? This might not be in the scope of this test but then why are we even doing that part?

2025-04-01 10:50 UTC, pranavrth commented on tests/0151-purge-brokers.c
> +        if (action == 2) {
```suggestion
        if (action == TEST_ACTION_SET_DOWN_BROKER) {
```
Is this what you mean?

2025-04-01 10:50 UTC, pranavrth commented on tests/0151-purge-brokers.c
> +        log_interceptor = NULL;
Instead of global variable, we should get this from the `rk` opaque. `do_test_add_remove_brokers` can return this.

2025-04-01 10:57 UTC, emasab commented on src/rdkafka_mock.c
> +                        rd_kafka_mock_coord_destroy(mcluster, mcoord);
In the mock cluster you can have coordinators for multiple consumer groups and the coordinator can be the same broker for all those groups so it's possible there are more than one.

2025-04-01 11:13 UTC, emasab commented on src/rdkafka_mock.c
> +rd_kafka_mock_cluster_reassing_partitions(rd_kafka_mock_cluster_t *mcluster) {
Maybe `rd_kafka_mock_cluster_reassign_partitions` with the typo fixed? `reassigning_partitions` seems more a question than a command

2025-04-01 11:21 UTC, emasab commented on tests/0151-purge-brokers.c
> +                TEST_ASSERT(actual_broker_ids[i] == expected_broker_ids[i],
There's the change to return `rd_kafka_brokers_learned_ids` from `rk_broker_by_id` that is sorted. So it's ensured. I can add it to the function documentation.

2025-04-01 11:24 UTC, emasab commented on tests/0151-purge-brokers.c
> +                           size_t expected_broker_ids_cnt,
The count must be the same, after every action there's an `expected_broker_ids`.
```C
 *        After each action, the client is expected to have the broker
 *        ids in \p expected_broker_ids and the count to be
 *        \p expected_brokers_cnt .
```

2025-04-01 11:28 UTC, emasab commented on tests/0151-purge-brokers.c
> +                if (action > 0) {
I don't think it improves readability because there are N actions it's expected there are N+1 states including the initial state. Here it's ensuring that we're in the initial state before executing the first action.

2025-04-01 11:36 UTC, emasab commented on tests/0151-purge-brokers.c
> +            {TEST_ACTION_SET_GROUP_COORDINATOR, 5},
Because if the coordinator doesn't change before removing a broker, that's returned by the `FindCoordinator` request and added again because it's needed as a reference in `rkcg_curr_coord`. So it continues adding that broker again and doesn't reach the desired number of brokers.
In a real cluster this doesn't happen as a new coordinator is elected before the broker shuts down so it's simulating that behaviour.
Initially I wanted to make the coordinator change automatic but that isn't the previous mock cluster contract so I added these manual commands.

2025-04-01 11:39 UTC, emasab commented on tests/0151-purge-brokers.c
> +        if (action == 2) {
No, here it's the action number that is passed (starting from 1) not the action type

2025-04-01 11:51 UTC, emasab commented on tests/0151-purge-brokers.c
> +        log_interceptor = NULL;
ok, just I return it as `void *`  to avoid making it coupled with this test.

2025-04-01 11:53 UTC, pranavrth commented on src/rdkafka_mock.c
> +rd_kafka_mock_cluster_reassing_partitions(rd_kafka_mock_cluster_t *mcluster) {
Works.

2025-04-01 11:54 UTC, pranavrth commented on tests/0151-purge-brokers.c
> +                TEST_ASSERT(actual_broker_ids[i] == expected_broker_ids[i],
Yes but the list of `expected_broker_ids` is defined by the user which might not be sorted. Its better to sort it.

2025-04-01 11:56 UTC, pranavrth commented on tests/0151-purge-brokers.c
> +                if (action > 0) {
I am talking about initial state. This seems like a hardcoding for the initial state. We can skip this if condition if we just add new action to do nothing.

2025-04-01 15:02 UTC, pranavrth commented on src/rdkafka_metadata.c
> +                rd_bool_t remove_configure_broker =
This field is removed altogether.

2025-04-01 15:34 UTC, emasab commented on tests/0149-broker-same-host-port.c
> +                rd_usleep(100000, 0);
ok

2025-04-01 15:43 UTC, pranavrth commented on src/rdkafka_broker.c
> +        return ids;
The function is changed. Not needed.

2025-04-01 16:30 UTC, pranavrth commented on tests/0149-broker-same-host-port.c
> +                rd_usleep(100000, 0);
Anything is fine.

2025-04-01 16:55 UTC, emasab commented
/sem-approve

2025-04-01 16:59 UTC, emasab approved these changes
Approving as I was initially reviewing. Thanks @pranavrth and @mfleming !

2025-04-01 17:07 UTC, emasab commented
/sem-approve

2025-04-01 17:18 UTC, emasab commented
/sem-approve

2025-04-01 17:46 UTC, pranavrth approved these changes
LGTM! Thanks @emasab and @mfleming !!

2025-04-01 17:49 UTC, merged