Fix duplicate messages when resuming
confluentinc/librdkafka pull request #4636
Opened 2024-03-06 15:50 UTC by emasab

Fixed a bug causing duplicate message consumption from a stale fetch start offset in some particular cases.

In case of subscription change with a consumer using the cooperative assignor it could resume fetching from a previous position.
That could also happen if resuming a partition that wasn't paused.

Fixed by ensuring that a resume operation is completely a no-op when the partition isn't paused.

2024-03-06 16:00 UTC, emasab commented
Fixes https://github.com/confluentinc/librdkafka/issues/4637

2024-03-22 09:03 UTC, pranavrth requested changes
Looks fine. Just few minor changes.

2024-03-22 09:03 UTC, pranavrth commented on tests/0145-unnecessary_resume_mock.c
> +static void test_no_duplicate_messages_unnecessary_resume(
Name of the test should be better. It can be `pause_resume_mock`.

2024-03-22 09:03 UTC, pranavrth commented on tests/0145-unnecessary_resume_mock.c
I was thinking to define a better numbering for mock tests. Integration tests starts with '0', unit test with '8', so we can use mock tests with '4' maybe?

2024-03-22 09:03 UTC, pranavrth commented on tests/test.c
> -
Keep extra line.

2024-03-22 09:03 UTC, pranavrth commented on tests/0145-unnecessary_resume_mock.c
> +        TEST_SAY("Unnecessary resume\n");
Is this test failing before the change?

2024-04-10 08:12 UTC, pranavrth approved these changes
LGTM!

2024-04-10 08:46 UTC, merged