Added new error code handling to OffsetCommit and OffsetFetch
confluentinc/librdkafka pull request #4672
Opened 2024-04-04 10:21 UTC by pranavrth

2025-09-05 17:32 UTC, emasab requested changes
Thanks for the tests @pranavrth ! Have these comments.

2025-09-05 17:32 UTC, emasab commented on src/rdkafka_cgrp.c
> +        rkcg->rkcg_generation_id = member_epoch;
Remove the same assignment at line 3123

2025-09-05 17:32 UTC, emasab commented on tests/test.c
> +    _TEST(0148_offset_fetch_commit_error_mock, TEST_F_LOCAL),
This tests is only for KIP-848 it would be better to name it so it says: this is for KIP-848 OffsetFetch and OffsetCommit , errors but also anything else. So:
```suggestion
    _TEST(0148_consumer_group_consumer_offset_fetch_commit_mock, TEST_F_LOCAL),
```

2025-09-05 17:32 UTC, emasab commented on tests/test.c
>      _TEST(0153_memberid, 0, TEST_BRKVER(0, 4, 0, 0)),
This tests is also for KIP-848 only, it would be better:
```suggestion
    _TEST(0153_consumer_group_consumer_memberid, 0, TEST_BRKVER(0, 4, 0, 0)),
```

2025-09-05 17:32 UTC, emasab commented on win32/tests/tests.vcxproj
> +    <ClCompile Include="..\..\tests\0148-offset_fetch_commit_error_mock.c" />
Reflect the changes in test naming, in `CMakeLists.txt` too

2025-09-05 17:32 UTC, emasab commented on tests/0148-offset_fetch_commit_error_mock.c
> + * Copyright (c) 2023, Confluent Inc.
Should be 2025, copyright is per file and starts when file is created and updated when file is updated.

2025-09-05 17:32 UTC, emasab commented on tests/0148-offset_fetch_commit_error_mock.c
> +        do_test_OffsetFetch_stale_member_error(mcluster, bootstraps);
Could call both this and `do_test_OffsetCommit_automatic_stale_member` with `stale_member_epoch`
```suggestion
        do_test_OffsetFetch_stale_member_epoch(mcluster, bootstraps);
```
and `do_test_OffsetCommit_automatic_stale_member_epoch`

2025-09-05 17:32 UTC, emasab commented on tests/0148-offset_fetch_commit_error_mock.c
> +    int variation) {
Use an `enum` for variations as in other tests.

2025-09-05 17:32 UTC, emasab commented on tests/0148-offset_fetch_commit_error_mock.c
> +        rd_kafka_mock_set_group_consumer_session_timeout_ms(mcluster, 10000);
Can reduce session timeout to 3s and hearthbeat interval to 1s with `rd_kafka_mock_set_group_consumer_heartbeat_interval_ms`.

2025-09-05 17:32 UTC, emasab commented on tests/0148-offset_fetch_commit_error_mock.c
> +                    RD_KAFKA_RESP_ERR_UNKNOWN_MEMBER_ID);
Just a single error should be enough for the session timeout. After that is retries the HB and that returns the error that causes the consumer leaving the group. If you delay the response for some time the session will expire and the HB will return that error as well.
Better to use some constants for session timeout and HB interval.

```suggestion
                rd_kafka_mock_broker_push_request_error_rtts(
                    mcluster, coordinator, RD_KAFKAP_OffsetCommit, 1,
                    RD_KAFKA_RESP_ERR_UNKNOWN_MEMBER_ID,
                    session_timeout_ms + heartbeat_interval_ms);
```

2025-09-05 17:32 UTC, emasab commented on tests/0148-offset_fetch_commit_error_mock.c
> +                rd_sleep(1);
Instead of sleeping here you can set a log interceptor and with mutex and condition broadcast the event that partition was committed (case 2) or lost (case 3).
For case 2 you can look for the log message "cgrp auto commit timer: returned: Success" while for case 3: "current assignment of 1 partition(s) lost: member fenced"

2025-09-05 17:32 UTC, emasab commented on tests/0148-offset_fetch_commit_error_mock.c
> +        /* First sequence of stale member epoch for 2 s */
These are permanent error and are retried at `auto.commit.interval.ms` if you set the configuration value to 1s here it becomes 4 seconds.
```suggestion
        /* First sequence of stale member epoch for 4 s */
```

2025-09-05 17:32 UTC, emasab commented on src/rdkafka_cgrp.c
> +                err = RD_KAFKA_RESP_ERR__OUTDATED;
Was checking by putting an assert and this condition isn't tested. Have a strategy for writing a test, let's talk about it.

2025-09-10 08:30 UTC, pranavrth commented on tests/test.c
> +    _TEST(0148_offset_fetch_commit_error_mock, TEST_F_LOCAL),
I don't agree that we should name tests based on the protocol. We should adjust the tests as we add more protocols like KIP-932. I would prefer to keep the name like this.

2025-09-17 08:52 UTC, emasab requested changes
Thanks Pranav, just suggesting some improvements for the change log entries.

2025-09-17 08:52 UTC, emasab commented on CHANGELOG.md
> +* Fix a condition where error was being raised in commit due to old error in the topic partition. (#4672)
```suggestion
* Fix for an error being raised after a commit due to an existing error in the topic partition (#4672).
```

2025-09-17 08:52 UTC, emasab commented on CHANGELOG.md
> +* Fix discarding consumer group heartbeat response without epoch update when leaving during inflight HB. (#4672)
```suggestion
* Fix for discarding the member epoch in a consumer group heartbeat response when leaving with an inflight HB (#4672).
```

2025-09-17 09:09 UTC, emasab approved these changes
Thanks for the fixes @pranavrth ! Let's later add a detail for the second fix that should be happening with the classic protocol too.

2025-09-17 11:07 UTC, merged