Mock handlers: Metadata handler upgrade to version 12
confluentinc/librdkafka pull request #4735
Opened 2024-05-29 07:22 UTC by emasab

and offset leader epoch fix in ListOffsets

2024-05-30 10:39 UTC, pranavrth requested changes

2024-05-30 10:39 UTC, pranavrth commented on src/rdkafka_mock_handlers.c
> +        }
When requesting by topic id, we should always return requested topic id in the response instead of ZERO_UUID.

2024-05-30 10:39 UTC, pranavrth commented on src/rdkafka_mock_handlers.c
> +                                topic_name = rktpar->topic;
I think if the `mtopic` is not found, we should not send incorrect topic name which was sent in the request. Lets also check what real broker is doing.

2024-05-30 10:39 UTC, pranavrth commented on src/rdkafka_mock_handlers.c
> +                        if (!mtopic && rktpar->topic && AllowAutoTopicCreation)
Change `rktpar->topic` to `topic_name`

2024-05-30 10:39 UTC, pranavrth commented on src/rdkafka_mock_handlers.c
>                                      mcluster, rktpar->topic, -1, &err);
Here as well.

2024-05-30 10:39 UTC, pranavrth commented on src/rdkafka_mock_handlers.c
>                                  err = RD_KAFKA_RESP_ERR_UNKNOWN_TOPIC_OR_PART;
If topic_id was present in the request, we should send `UNKNOWN_TOPIC_ID` error instead in v12.

2024-05-31 15:16 UTC, pranavrth requested changes
Minor comments.

2024-06-03 10:09 UTC, emasab commented on src/rdkafka_mock_handlers.c
> +                }
The broker code is validating it after reading it and returning INVALID_REQUEST error in that case so I did the same

2024-06-03 10:10 UTC, emasab commented on src/rdkafka_mock_handlers.c
> +                            (!RD_KAFKA_UUID_IS_ZERO(topic_id) || !topic_name);
same

2024-06-03 10:39 UTC, pranavrth commented on src/rdkafka_mock_handlers.c
> +                                topic_name = rktpar->topic;
My bad.

2024-06-05 08:47 UTC, pranavrth approved these changes
LGTM.!

2024-06-06 07:23 UTC, pranavrth approved these changes

2024-06-06 07:25 UTC, merged