Fix for an infinite loop in cooperative sticky assignor
confluentinc/librdkafka pull request #4800
Opened 2024-07-31 16:12 UTC by emasab

when potential topic partitions are less than number of members.

Closes #4783

2024-07-31 16:24 UTC, mensfeld commented
I can confirm this works :) I applied it via a patch in rdkafka-ruby and was not able to trigger it anymore. Thank you!

2024-07-31 17:13 UTC, emasab commented
Thank you @mensfeld ! Couldn't push it earlier because we're reviewing company flows after the incident that happened to public repositories earlier in the month.

2024-07-31 18:28 UTC, mensfeld commented
No worries. You motivated me to finally craft ability to patch librdkafka for rdkafka-ruby so now I can also expose the needed fork-protect APIs for MacOS. Thank you for all your hard work :pray:

2024-07-31 18:32 UTC, mensfeld approved these changes

2024-10-16 07:11 UTC, pranavrth requested changes
Thanks. Please rebase and we should be good to merge.

2024-10-16 07:38 UTC, pranavrth approved these changes
LGTM!. We can add a test but I don't feel there is necessity of a test for this kind of bug.

2024-10-16 08:26 UTC, pranavrth commented
@mensfeld - I was saying that we don't need a test for this kind of trivial bug.

2024-10-16 08:26 UTC, pranavrth approved these changes
LGTM!.

2024-10-16 08:46 UTC, merged