Fallback to fetch v12 (#10)
confluentinc/librdkafka pull request #4806
Opened 2024-08-08 08:23 UTC by anchitj

If any toppars have a zero topic id

### How to Reproduce
Set inter.broker.protocol.version to 2.4 with 3.7 and fetch would fail always.

2024-08-08 08:27 UTC, anchitj commented on src/rdkafka_fetcher.c
> + * @brief Check if any toppars have a non-zero topic id.
Will change to `zero topic id`

2024-08-16 11:45 UTC, anchitj commented on src/rdkafka_fetcher.c
> +         * inter.broker.protocol.version is old */
Change old to <2.8

2024-09-16 11:42 UTC, emasab requested changes
Thanks for the fix! Let's make your changes and my comment and rebase it, then I'm approving

2024-09-24 13:21 UTC, emasab approved these changes
LGTM Thanks Anchit

2024-09-24 14:12 UTC, merged