KIP 848: Added support for DescribeConsumerGroup for consumer protocol groups
confluentinc/librdkafka pull request #4941
Opened 2024-12-27 11:22 UTC by PratRanj07

This PR intends to add support for calling DescribeConsumerGroups for groups created with the new consumer protocol and add backward compatibility to describe group created with the old Classic Protocol.
The working of the API remains similar. Users will continue to call the existing DescribeConsumerGroups api but internally we will be calling the new ConsumerGroupDescribe api to fetch the results. If we get GRP_NOT_FOUND or UNSUPPORTED_VERSION error, then in that case we will call the old DescribeConsumerGroup api.

2025-02-07 07:30 UTC, pranavrth requested changes
First pass comments.

2025-02-07 07:30 UTC, pranavrth commented on src/rdkafka_admin.c
> +                 RD_KAFKA_RESP_ERR_UNSUPPORTED_VERSION)) {
Check for memory leak in this condition as well.

2025-02-12 11:38 UTC, PratRanj07 commented on src/rdkafka.h
> +
It is giving NULL as default value in these cases. I have updated it in the comments

2025-04-10 22:52 UTC, pranavrth requested changes
Comments on Implementation part.

2025-04-10 22:52 UTC, pranavrth commented on src/rdkafka_admin.c
> +        int32_t cnt;
```suggestion
        int32_t groups_cnt;
```

2025-04-10 22:52 UTC, pranavrth commented on src/rdkafka_admin.c
> +        int32_t group_epoch, assignment_epoch;
Move these two to inner for loop.
Change to `GroupEpoch` and `AssignmentEpoch`.

Do these for all the data points we are getting from the protocol.

2025-04-10 22:52 UTC, pranavrth commented on src/rdkafka_admin.c
> +                            SubscribedTopicRegex = RD_KAFKAP_STR_INITIALIZER;
Why initializing? This is not needed.

2025-04-10 22:52 UTC, pranavrth commented on src/rdkafka_admin.c
> +                rd_kafka_op_destroy(rko_result);
`RD_IF_FREE`

2025-04-10 22:52 UTC, pranavrth commented on src/rdkafka_admin.c
> +                rko_fanout->rko_u.admin_request.fanout.outstanding++;
Explain this in comments.

2025-04-10 22:52 UTC, pranavrth commented on src/rdkafka_admin.c
> +                 RD_KAFKA_RESP_ERR_UNSUPPORTED_VERSION)) {
Explain what we are doing here in comments.

2025-04-10 22:52 UTC, pranavrth commented on src/rdkafka_op.h
> +        RD_KAFKA_OP_CONSUMERGROUPDESCRIBE, /**< Admin:
I think this is not needed altogether. Try using the old one only.

2025-04-10 22:52 UTC, pranavrth commented on src/rdkafka_request.c
> +        rd_kafka_buf_finalize_arraycnt(rkbuf, ofGroupsArrayCnt, group_cnt);
```suggestion
        rd_kafka_buf_write_arraycnt(rkbuf, group_cnt);
```

2025-04-10 22:52 UTC, pranavrth commented on src/rdkafka_request.c
> +        }
Write in same order as request.

2025-04-11 08:25 UTC, pranavrth commented on src/rdkafka.h
> +
Let it be as it is as this is getter function.

2025-04-11 13:34 UTC, PratRanj07 commented on src/rdkafka_request.c
> +        if (ApiVersion == -1) {
As discussed on Slack, removed this check, in case of fetaure not supported error we will fallback to the old protocol.

2025-04-11 20:57 UTC, pranavrth requested changes

2025-04-11 20:57 UTC, pranavrth commented on src/rdkafka_proto.h
> +            [RD_KAFKAP_ConsumerGroupDescribe] = "ConsumerGroupDescribeRequest",
align '=' with above.

2025-04-11 20:57 UTC, pranavrth commented on src/rdkafka_admin.c
> +             *client_host                   = NULL;
Merge these two

2025-04-11 20:57 UTC, pranavrth commented on src/rdkafka_admin.c
> +                        client_host = RD_KAFKAP_STR_DUP(&ClientHost);
This is leaking. Free them after using and assign them as NULL.

2025-04-11 20:57 UTC, pranavrth commented on src/rdkafka_admin.c
> +                      RD_KAFKA_EVENT_CONSUMERGROUPDESCRIBE_RESULT);
We can have only 1 of these. Keep the older one.

2025-04-11 20:57 UTC, pranavrth commented on src/rdkafka.h
> +
We should remove the new function. there is no field like `target_partitions` in MemberAssignment. We should modify `rd_kafka_MemberAssignment_partitions` like earlier.

2025-04-11 21:49 UTC, PratRanj07 commented on src/rdkafka_proto.h
> +            [RD_KAFKAP_ConsumerGroupDescribe] = "ConsumerGroupDescribeRequest",
Aligning it is resulting in style fix error.

2025-04-14 06:53 UTC, pranavrth commented on src/rdkafka.h
> +rd_kafka_consumer_group_type_t rd_kafka_ConsumerGroupDescription_type(
Change this to `rd_kafka_GroupType_t`

2025-04-14 06:54 UTC, pranavrth commented on src/rdkafka.h
> + *         It returns NULL for the `classic` group types.
```suggestion
 *         Returns NULL for the `classic` group types.
```

2025-04-14 06:58 UTC, pranavrth commented on src/rdkafka_admin.c
> +                            member->target_assignment->partitions);
Use RD_IF_FREE for this and other if conditions in the function.

2025-04-14 07:03 UTC, pranavrth commented on src/rdkafka_admin.c
> +                return NULL;
```suggestion
        if (!assignment)
                return NULL;
        return assignment->partitions;
```

2025-04-14 08:06 UTC, pranavrth commented on src/rdkafka.h
> +rd_kafka_consumer_group_type_t rd_kafka_ConsumerGroupDescription_type(
Adding this to changes required for major version upgrade.

2025-04-14 09:01 UTC, pranavrth requested changes

2025-04-14 10:56 UTC, pranavrth requested changes

2025-04-14 10:56 UTC, pranavrth commented on tests/0081-admin.c
> +                }
Use `protocols` directly instead of this if-else.


```suggestion
                test_conf_init(&conf, NULL, 0);
                test_conf_set(conf, "group.protocol", protocols[i]);
```

2025-04-14 10:56 UTC, pranavrth commented on tests/0081-admin.c
> +                test_conf_set(conf, "session.timeout.ms", "5000");
This property is not needed for this test.

2025-04-14 10:56 UTC, pranavrth commented on tests/0081-admin.c
> +        }
We can extract this functionality into a method in the same file or in `test.c` file which can be used by other functions in this test file.

2025-04-14 10:56 UTC, pranavrth commented on tests/0081-admin.c
> +                rd_kafka_resp_err_t exp_err                    = exp->err;
Use expected[i] directly.

2025-04-14 10:56 UTC, pranavrth commented on tests/0081-admin.c
> +                }
Why are we not checking the type here?

2025-04-14 10:56 UTC, pranavrth commented on src/rdkafka_admin.c
> +        host = rd_strdup(rkb->rkb_origname);
Free node as well.

2025-04-14 11:20 UTC, pranavrth requested changes

2025-04-14 11:20 UTC, pranavrth commented on tests/0081-admin.c
> +                                                             mainq, 1500);
These all test can be tested in all the scenarios starting Broker version 4.0. Including if condition as well.

2025-04-14 11:20 UTC, pranavrth commented on tests/0081-admin.c
> +                        test_conf_set(conf, "group.protocol", "consumer");
This is overriden in the `test_create_consumer()` function. This test would fail in that case if we test for the type as well.

2025-04-14 13:14 UTC, pranavrth commented on src/rdkafka_admin.c
> +                        instance_id = RD_KAFKAP_STR_DUP(&InstanceId);
This can be NULL. It will be a Segmentation fault in this case. Fix this.

2025-04-14 13:28 UTC, pranavrth requested changes

2025-04-14 13:28 UTC, pranavrth commented on src/rdkafka_admin.c
> +        rd_kafka_buf_skip_tags(reply);
```suggestion
        rd_kafka_buf_skip_tags(reply);

        RD_IF_FREE(host, rd_free);
        RD_IF_FREE(node, rd_kafka_Node_destroy);
```

2025-04-14 13:28 UTC, pranavrth commented on src/rdkafka_admin.c
> +            (groupres->type == RD_KAFKA_CONSUMER_GROUP_TYPE_CONSUMER &&
Check `RD_KAFKA_CONSUMER_GROUP_TYPE_CONSUMER` for  `UNSUPPORTED_FEATURE` error as well. If we get this error (which might happen in old brokers), we will keep on looping.

2025-04-14 17:58 UTC, emasab requested changes
Thanks Pratyush, these are my comments about the PR

2025-04-14 17:58 UTC, emasab commented on examples/describe_consumer_groups.c
> +            rd_kafka_MemberAssignment_partitions(target_assignment);
This function shouldn't check the argument is NULL, instead it mustn't be called with a NULL argument.
```suggestion
            target_assignment
                ? rd_kafka_MemberAssignment_partitions(target_assignment)
                : NULL;
```

2025-04-14 17:58 UTC, emasab commented on examples/describe_consumer_groups.c
>              " state %s%s, with %" PRId32 " member(s)\n",
As with other field let's add the quotes
```suggestion
            " state \"%s\"%s, with %" PRId32 " member(s)\n",
```

2025-04-14 17:58 UTC, emasab commented on src/rdkafka_admin.c
> +                return NULL;
Same, here it shouldn't check for NULL

2025-04-14 17:58 UTC, emasab commented on src/rdkafka_admin.c
> +    rd_kafka_consumer_group_type_t type) {
Let's remove this parameter, see :
```suggestion
    ) {
```

2025-04-14 17:58 UTC, emasab commented on src/rdkafka_admin.c
> +            RD_KAFKA_CONSUMER_GROUP_STATE_UNKNOWN, type, NULL, error);
```suggestion
            RD_KAFKA_CONSUMER_GROUP_STATE_UNKNOWN, RD_KAFKA_CONSUMER_GROUP_TYPE_UNKNOWN, NULL, error);
```

2025-04-14 17:58 UTC, emasab commented on src/rdkafka_admin.c
> +rd_kafka_ConsumerGroupDescribeResponseParse(rd_kafka_op_t *rko_req,
```suggestion
rd_kafka_ConsumerGroupDescribeResponse_parse(rd_kafka_op_t *rko_req,
```

2025-04-14 17:58 UTC, emasab commented on src/rdkafka_admin.c
> +static rd_bool_t do_fallback_to_old_consumer_group_descibe(
```suggestion
static rd_bool_t rd_kafka_admin_describe_consumer_group_fallback_to_classic(
```

2025-04-14 17:58 UTC, emasab commented on src/rdkafka_admin.c
> +static void rd_kafka_create_describe_group_admin_request(
```suggestion
static void rd_kafka_admin_describe_consumer_group_request(
```

2025-04-14 17:58 UTC, emasab commented on src/rdkafka_admin.c
> +                        rd_kafka_buf_skip_tags(reply);
```suggestion
                        /* Assignment tags */
                        rd_kafka_buf_skip_tags(reply);
```

2025-04-14 17:58 UTC, emasab commented on src/rdkafka_admin.c
> +                        rd_kafka_buf_skip_tags(reply);
```suggestion
                        /* TargetAssignment tags */
                        rd_kafka_buf_skip_tags(reply);
```

2025-04-14 17:58 UTC, emasab commented on src/rdkafka_admin.c
> +                        rd_kafka_buf_skip_tags(reply);
```suggestion
                        /* Member tags */
                        rd_kafka_buf_skip_tags(reply);
```

2025-04-14 17:58 UTC, emasab commented on src/rdkafka_request.c
> + *        to use the maximum available version.
`max_ApiVersion` isn't passed here
```suggestion
```

2025-04-14 17:58 UTC, emasab commented on src/rdkafka_admin.c
> +        rd_kafka_buf_read_arraycnt(reply, &groups_cnt, 100000);
```suggestion
        rd_kafka_buf_read_arraycnt(reply, &groups_cnt, RD_KAFKAP_GROUPS_MAX);
```

2025-04-14 19:11 UTC, pranavrth commented on src/rdkafka_request.c
> +            rkb, RD_KAFKAP_ConsumerGroupDescribe, 0, 0, NULL);
This returns the error on the request part itself and then the admin worker fails. We removed it during the review. Check - https://github.com/confluentinc/librdkafka/blob/85b9cb4cf2126e215176dad8f07c53491112fc33/src/rdkafka_admin.c#L8176-L8186

We are getting same error in the response merge function if we remove it from here through `rd_kafka_send` I think.

2025-04-14 19:52 UTC, emasab commented on src/rdkafka_request.c
> +            rkb, RD_KAFKAP_ConsumerGroupDescribe, 0, 0, NULL);
In case returning this error as in other requests, the duplicate 
```C
rd_kafka_enq_once_del_source(eonce, "coordinator response");
```
on `rd_kafka_admin_coord_request` should be removed otherwise it the eonce id destroyed before calling the callback.

2025-04-14 19:57 UTC, emasab commented on src/rdkafka_request.c
> +            rkb, RD_KAFKAP_ConsumerGroupDescribe, 0, 0, NULL);
> We are getting same error in the response merge function if we remove it from here through rd_kafka_send I think.

Yes the error is returned by `rd_kafka_send` but it's not correct to continue with request construction if the `ApiVersion` is -1

2025-04-14 21:02 UTC, PratRanj07 commented on src/rdkafka_request.c
> +            rkb, RD_KAFKAP_ConsumerGroupDescribe, 0, 0, NULL);
Changed it to not fail when the admin result when request is `rd_kafka_admin_ConsumerGroupDescribeRequest` and the err returned is Unsupported feature

2025-04-14 22:05 UTC, pranavrth commented on src/rdkafka_request.c
> +            rkb, RD_KAFKAP_ConsumerGroupDescribe, 0, 0, NULL);
I don't know if this is correct to hardcode a condition for this specific case in general `rd_kafka_admin_coord_request` function. Let's understand this offline.

2025-04-15 06:49 UTC, emasab requested changes

2025-04-15 06:49 UTC, emasab commented on src/rdkafka_proto.h
> +            [RD_KAFKAP_ConsumerGroupDescribe]  = "ConsumerGroupDescribeRequest",
Remove `Request`  here and format the list 
```suggestion
            [RD_KAFKAP_ConsumerGroupDescribe]  = "ConsumerGroupDescribe",
```

2025-04-15 06:49 UTC, emasab commented on src/rdkafka_admin.c
> +                }
The `else if` block can be removed.

2025-04-15 06:49 UTC, emasab commented on src/rdkafka_admin.c
> +
Not necessary to declare it here as it's used after it's defined.

2025-04-15 06:49 UTC, emasab commented on src/rdkafka_admin.c
>                  rd_kafka_enq_once_del_source(eonce, "coordinator response");
We should keep this one generic, what I was suggesting is that we remove `rd_kafka_enq_once_del_source(eonce, "coordinator response");` here as it's causes a bug in these cases when we return without sending the request.
Let's discuss to validate this fix.
```suggestion
        if (err) {
```

2025-04-15 08:09 UTC, pranavrth requested changes

2025-04-15 08:09 UTC, pranavrth commented on src/rdkafka_admin.c
> +static rd_bool_t rd_kafka_admin_describe_consumer_group_fallback_to_classic(
```suggestion
static rd_bool_t rd_kafka_admin_describe_consumer_group_do_fallback_to_classic(
```

2025-04-15 08:09 UTC, pranavrth commented on src/rdkafka_admin.c
> +        return rd_false;
```suggestion
        return groupres->error &&
            (groupres->error->code == RD_KAFKA_RESP_ERR_GROUP_ID_NOT_FOUND ||
             groupres->error->code == RD_KAFKA_RESP_ERR_UNSUPPORTED_VERSION ||
             groupres->error->code == RD_KAFKA_RESP_ERR__UNSUPPORTED_FEATURE);
```

2025-04-15 09:02 UTC, emasab approved these changes
Thanks Prayush and Pranav! Approving

2025-04-15 09:42 UTC, pranavrth approved these changes
LGTM!.

2025-04-15 09:44 UTC, merged